version: '3.8'
services:
  database:
    image: mysql:latest
    ports:
      - "3308:3306"
    expose:
      - 3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  filesystem:
    build: "./filesystem"
    ports:
    - "7070:7070"
  api:
    build: "./api"
    depends_on:
      - database
      - filesystem
    restart: always
    ports:
      - "3001:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME} 
      JWT_KEY: ${JWT_KEY}
      filesystem: ${filesystem}
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
      
      # To avoid the infinite HMR error in console
      - "3003:3000"
    environment:
      VITE_API_HOST: ${API_HOST}
    depends_on:
      - api
